language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

compiler: clang

jdk:
  - openjdk8

mono:
  - latest

install:
  - mono --version
  - which java
  - java -version
  - echo $JAVA_HOME
  - source build/SetupCI.sh

script:
  - ./build.sh -t Travis -v diagnostic
